name: linkary
description: "Linkary Simplify your connection, Master your network."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+9

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  http: ^1.6.0
  freerasp: ^7.5.1
  crypto: ^3.0.7
  html: ^0.15.4
#  dartz: ^0.10.1
  iconsax:
  iconly: ^1.0.1
  flutter_secure_storage: ^10.0.0
  local_auth: ^3.0.1
  url_launcher: ^6.3.2
  google_fonts: ^8.0.2
  flutter_localizations:
    sdk: flutter
  qr_flutter: ^4.1.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.5
  vibration: ^3.1.8
  shared_preferences:
  fl_chart: ^1.2.0
  network_info_plus: ^8.1.0
  screenshot: ^3.0.0
  share_plus: ^13.1.0
  path_provider: ^2.1.5
  flutter_local_notifications: ^21.0.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  font_awesome_flutter: ^11.0.0
  package_info_plus: ^10.1.0
  tutorial_coach_mark: ^1.3.3
  flutter_background_service: ^5.1.0
  workmanager: ^0.9.0+3
  cached_network_image: ^3.4.1
  permission_handler: ^11.3.1
  in_app_update: ^4.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default:21

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
